extensions:
  oauth2client:
    client_id: ${UAA_CLIENT_ID}
    client_secret: ${UAA_CLIENT_SECRET}
    token_url: ${UAA_TOKEN_URL}
    tls:
      insecure: true
    timeout: 2s

receivers:
  cloudfoundry:
    rlp_gateway:
      endpoint: ${RLP_GATEWAY_ENDPOINT}
    uaa:
      url: ${UAA_TOKEN_URL}
      password: ${UAA_PASSWORD}

processors:
  resourcedetection:
    system:

exporters:
  signalfx:
    access_token: ${SPLUNK_ACCESS_TOKEN}
    realm: ${SPLUNK_REALM}
    api_url: ${SPLUNK_API_URL}
    ingest_url: ${SPLUNK_INGEST_URL}

service:
  extensions: [oauth2client]
  pipelines:
    metrics:
      receivers: [cloudfoundry]
      processors: [resourcedetection]
      exporters: [signalfx]
