receivers:
  cloudfoundry:
    rlp_gateway:
      endpoint: ${RLP_GATEWAY_ENDPOINT}
      shard_id: ${RLP_GATEWAY_SHARD_ID}
      tls:
        insecure_skip_verify: ${RLP_GATEWAY_TLS_INSECURE}
    uaa:
      endpoint: ${UAA_ENDPOINT}
      client_id: ${UAA_CLIENT_ID}
      client_secret: ${UAA_CLIENT_SECRET}
      tls:
        insecure_skip_verify: ${UAA_TLS_INSECURE}

processors:
  resourcedetection:
    system:

exporters:
  signalfx:
    access_token: ${SPLUNK_ACCESS_TOKEN}
    realm: ${SPLUNK_REALM}
    api_url: ${SPLUNK_API_URL}
    ingest_url: ${SPLUNK_INGEST_URL}

service:
  extensions: [oauth2client]
  pipelines:
    metrics:
      receivers: [cloudfoundry]
      processors: [resourcedetection]
      exporters: [signalfx]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [signalfx]

extensions:
  oauth2client:
    client_id: ${UAA_CLIENT_ID}
    client_secret: ${UAA_CLIENT_SECRET}
    token_url: ${UAA_TOKEN_URL}
    timeout: 10s